In [2]:
import cv2 as cv
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myArray = np.array(mylist)

In [6]:
myArray

array([1, 2, 3])

In [7]:
type(myArray)

numpy.ndarray

In [8]:
np.arange(0, 10, )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2) #Start end and step size

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
type(0)

int

In [14]:
type(0.0)

float

In [15]:
type(.0)

float

In [16]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10) #lower limit and then the higher limit and than the number of random number we want

In [20]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [21]:
arr.max()

95

In [25]:
arr.argmax() #This gives the index of max value in array

0

In [23]:
arr.min()

9

In [26]:
arr.argmin() #This gives the index of min value in array

7

In [27]:
arr.mean()

60.8

In [28]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [29]:
mat = np.arange(0,100).reshape(10, 10)

In [30]:
mat.shape

(10, 10)

In [31]:
row = 0
col = 1
mat[row,col]

1

In [32]:
mat[:, 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [33]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [34]:
mat[1, :]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
mat[1, :].reshape(10,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [36]:
mat[0:3, 0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])